"""
sage_utils.py

Utility helpers for file IO, simple HTML generation, and result paths.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

import os


RESULTS_DIR = Path(__file__).resolve().parent / "results"


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def save_json(data: Any, path: Path) -> None:
    ensure_dir(path.parent)
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)


def save_text(text: str, path: Path) -> None:
    ensure_dir(path.parent)
    path.write_text(text, encoding="utf-8")


def render_simple_html(title: str, body: str) -> str:
    return (
        "<!doctype html><html><head><meta charset='utf-8'><title>" + title + "</title></head>"
        "<body><main>" + body + "</main></body></html>"
    )


def results_subdir(*parts: str) -> Path:
    path = RESULTS_DIR.joinpath(*parts)
    ensure_dir(path)
    return path


__all__ = [
    "RESULTS_DIR",
    "ensure_dir",
    "save_json",
    "save_text",
    "render_simple_html",
    "results_subdir",
    "load_prompts",
    "save_final_results",
    "str2dict",
]


def load_prompts(path_to_prompts: str) -> Tuple[str, str]:
    """Load system and user prompts from text files in a directory.
    
    DEPRECATED: This function is no longer used in the 3-layer architecture.
    All prompts are now dynamically generated by sage_prompt_generator.
    Kept for backward compatibility only.
    """
    base = Path(path_to_prompts)
    system_path = base / "system_prompt.txt"
    user_path = base / "user_prompt.txt"
    system_text = system_path.read_text(encoding="utf-8") if system_path.exists() else ""
    user_text = user_path.read_text(encoding="utf-8") if user_path.exists() else ""
    return system_text, user_text


def save_final_results(log: Any, path_to_save: str, filename: str = "final_log.json") -> None:
    """Persist the experiment log to the given results directory."""
    out_dir = Path(path_to_save)
    ensure_dir(out_dir)
    save_json(log, out_dir / filename)


def str2dict(spec: str) -> Dict[str, Any]:
    """Parse a simple layer-to-features spec string into a dict.

    Example inputs:
    - "layer15=808"
    - "layer15=808,809;layer16=1,2"
    """
    result: Dict[str, Any] = {}
    if not spec:
        return result
    # Split by ';' to get groups
    groups = [g.strip() for g in spec.split(";") if g.strip()]
    for group in groups:
        if "=" not in group:
            continue
        key, vals = group.split("=", 1)
        key = key.strip()
        features = []
        for v in vals.split(","):
            v = v.strip()
            if not v:
                continue
            try:
                features.append(int(v))
            except ValueError:
                # keep raw if not int
                features.append(v)
        result[key] = features
    return result


